<a href="https://colab.research.google.com/github/psaw/hse-ai24-dl/blob/stepik/stepik/4.2%20-%20IntroToPyTorch_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [2]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [3]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [4]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [5]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание 1

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

**Ответ:** 1.58

In [8]:
# ваш код здесь
a @ a.T

array([[1.57995312, 0.48673782, 1.28525324, 0.9947397 , 0.64675177],
       [0.48673782, 0.40706809, 0.26368252, 0.57840584, 0.55984141],
       [1.28525324, 0.26368252, 1.11497408, 0.64198458, 0.34157207],
       [0.9947397 , 0.57840584, 0.64198458, 1.44251562, 0.77015453],
       [0.64675177, 0.55984141, 0.34157207, 0.77015453, 0.77110897]])

In [9]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [10]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание 2

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

**Ответ:** 333383335000

In [23]:
# ваш код здесь
np.sum(np.arange(1, 10001) ** 2)

np.int64(333383335000)

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [15]:
x = torch.rand(5, 3)
x

tensor([[0.5056, 0.7808, 0.6443],
        [0.2198, 0.9968, 0.8404],
        [0.2077, 0.9295, 0.0513],
        [0.3623, 0.2540, 0.7971],
        [0.2444, 0.6596, 0.9502]])

In [16]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [17]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.5056, 5.7808, 5.6443],
        [5.2198, 5.9968, 5.8404],
        [5.2077, 5.9295, 5.0513],
        [5.3623, 5.2540, 5.7971],
        [5.2444, 5.6596, 5.9502]])



In [18]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.2804, 1.4309, 0.8639, 0.8951, 1.2509],
        [1.4309, 1.7482, 1.0153, 1.0027, 1.5098],
        [0.8639, 1.0153, 0.9098, 0.3522, 0.7127],
        [0.8951, 1.0027, 0.3522, 0.8311, 1.0135],
        [1.2509, 1.5098, 0.7127, 1.0135, 1.3977]])

X*X^T  (2):
tensor([[1.2804, 1.4309, 0.8639, 0.8951, 1.2509],
        [1.4309, 1.7482, 1.0153, 1.0027, 1.5098],
        [0.8639, 1.0153, 0.9098, 0.3522, 0.7127],
        [0.8951, 1.0027, 0.3522, 0.8311, 1.0135],
        [1.2509, 1.5098, 0.7127, 1.0135, 1.3977]])



In [19]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.6436, 0.6857, 0.3962, 0.4711, 0.6181])



In [20]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [29]:
torch.sum(torch.arange(1, 10001) ** 2)

tensor(333383335000)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [30]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [31]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.2567, 0.3872, 0.5859],
        [0.6869, 0.9268, 0.6191],
        [0.5428, 0.5799, 0.8684],
        [0.4683, 0.7527, 0.0909],
        [0.2913, 0.0955, 0.1574]])


In [32]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [33]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [34]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [35]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-0.0668,  2.2307,  0.4440],
        [ 0.0573,  0.6764, -0.2461],
        [-1.0201, -0.4610,  1.4419],
        [ 0.7789, -1.8056,  1.2261],
        [-0.6154,  0.2622, -0.4842]]) torch.Size([5, 3])


## Задание 3

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [40]:
import torch

torch.manual_seed(42)

# ваш код здесь
x = torch.rand(5, 3)
y = torch.rand(5, 3)

x + y

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])

In [39]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание 4

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [51]:
# your code here
# x.mm(y.transpose(0, 1))
x @ y.T

tensor([[1.4088, 0.9125, 0.9795, 0.4769, 0.6789],
        [1.1025, 0.6627, 1.0391, 0.4219, 0.4086],
        [1.3528, 0.8200, 1.1313, 0.5785, 0.4912],
        [1.2254, 0.7820, 0.8300, 0.4789, 0.5416],
        [1.3013, 0.7878, 1.1686, 0.5105, 0.4885]])

In [53]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [68]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [69]:
a = torch.rand((1,3))
a

tensor([[0.5832, 0.3376, 0.8090]])

In [75]:
a.squeeze(0)

tensor([0.5832, 0.3376, 0.8090])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [76]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [77]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [78]:
a @ b

array([70])

In [ ]:
# b @ a
